import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import LayoutWithNavBar from '../component/organisms/navbarLayout';
import GlobalVarCSS from '../component/globalVarCss';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Event Reigstration - ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <GlobalVarCSS />
          <LayoutWithNavBar >
            {children}
          </LayoutWithNavBar>
      </body>
    </html>
  )
}
